apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyagi-config
  labels: 
    first: app
spec: # Behaviour of replicaset
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec: # behavour of pod
      containers:
        - name: tyagi-shopkart
          image: himalayat/shopkart:v1.0
          ports:
            - containerPort: 8080