namespace:
  name: tyagi-config
replicas: 2
labels:
  app: veg-app
  containers:
    - name: tyagi-veg
      port: 3000
service:
  name: tyagi-service
  port: 80
  targetPort: 3000
  type: LoadBalancer
configMap:
  name: tyagi-config
  data:
    DB_HOST: mongodb
    DB_PORT: "27017"
    DB_USER: admin
    APP_NAME: vegetable_order
    APP_PORT: "3000"
secret:
  name: tyagi-secret
  type: Opaque
  data:
    DB_USER: LW4gImFkbWluIiANCg==
    DB_PASS: LW4gIkhpbWFsYXlhQDEyIiANCg==