apiVersion: apps/v1
kind: Deployment

metadata:
  name: tyagi-deployment
  labels:
    app: veg-app

spec:
  replicas: {{.values.replicas}}

  selector:
    matchLabels:
      app: veg-app

  template:
    metadata:
      labels:
        app: {{.values.labels.web}}

    spec:
      containers:
        - name: {{.values.containers.name}}
          image: {{.values.containers.image}}
          ports:
            - containerPort: {{.values.containers.port}}
          envFrom:
            - configMapRef:
                name: {{.values.configMap.name}}
            - secretRef:
                name: {{.values.secret.name}}

---

apiVersion: v1
kind: Service

metadata:
  name: {{.values.service.name}}

spec:
  selector:
    app: veg-app

  ports:
    - protocol: TCP
      port: {{.values.service.port}}
      targetPort: {{.values.service.targetport}}

  type: {{.values.service.type}}