apiVersion: v1
kind: Pod

metadata:
  name: tyagi-pod

spec:
  containers:
    - name: tyagi-shopkart
      image: himalayat/shopkart:v1.0
      ports:
        - containerPort: 8080

    - name: tyagi-nginx
      image: nginx
      ports:
        - containerPort: 80