apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: tyagi-rs
  labels:
    app: web

spec:
  replicas: 3
  selector: 
    matchLabels:
      web: nginx-cont
  
  template: 
    metadata:
      labels: 
        web: nginx-cont
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports: 
            - containerPort: 80